services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5215:5215"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/todo.db
    volumes:
      - ./backend/todo.db:/app/todo.db
    networks:
      - todo-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    environment:
      - API_URL=http://localhost:5215
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge 